services:
  data:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YvKjqWq5rdWHCTyDnm1W7UoxIJzNutPC4wR1wGnWHyfE2iNJJcJzGl68bVTvBxlf
    volumes:
      - sqldata:/var/opt/mssql
  bettyslotgame:
    image: bettyslotgame
    build:
      context: .
      dockerfile: BettySlotGame/Dockerfile
    network_mode: "host"
    stdin_open: true
    tty: true

volumes:
  sqldata:
